"""The demo shipping company.

**This carrier does not exist, and its voyages are not real.** No Maersk, MSC or
CMA CGM vessel appears anywhere in this product, and no real vessel's voyage is
represented. The fleet below belongs to a fictional operator so the Shipping
Company workspace has something coherent to reason about, and every surface that
shows it carries :data:`COMPANY_DISCLAIMER`.

What is architecturally real is the seam. :class:`CompanyProfile` and
:class:`FleetVessel` are what a real carrier account would populate, and
:func:`from_provider` is where a licensed AIS or fleet-management feed plugs in.
Every downstream consumer -- Global Eye exposure, cargo, advisories -- reads this
interface and not the demo data, so replacing the demo carrier with a real one is
a provider implementation and nothing else.

Vessel names are Indian Ocean geography, deliberately unlike any operating
carrier's naming convention, so a screenshot cannot be mistaken for a real fleet.
"""

from __future__ import annotations

import hashlib
import random
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from src.portwatch_os.global_eye.exposure import TRADE_LANES, VesselVoyage
from src.utils import port_registry, provenance

COMPANY_DISCLAIMER = (
    "Demo carrier. PortWatch Demo Shipping is a fictional operator created so "
    "the fleet workspace has a coherent subject. Its vessels, voyages, cargo and "
    "schedules are generated by this application and are not, and do not "
    "represent, any real carrier, vessel or commercial voyage. The company "
    "account interface is the seam a licensed fleet or AIS provider plugs into."
)

#: Where positions come from. Taken from the provenance vocabulary rather than
#: written out here, so a company fleet, the national picture and the pipeline's
#: own registry cannot drift into describing the same thing three ways.
SOURCE_SIMULATED = provenance.SIMULATED_TRAFFIC
SOURCE_LIVE_AIS = "LIVE_AIS"
SOURCE_PROVIDER = "FLEET_PROVIDER"


@dataclass
class FleetVessel:
    """One vessel in a company fleet, and the voyage it is running."""

    vessel_id: str
    name: str
    #: Always ``None`` for the demo fleet: no IMO number was issued to a
    #: fictional hull, and inventing one would make it look registrable.
    imo: Optional[str]
    vessel_class: str
    loa_m: float
    beam_m: float
    draught_m: float
    capacity_teu: int
    reefer_plugs: int
    service_speed_kn: float
    flag: str

    #: Current voyage.
    origin_port: Optional[str] = None
    destination_port: Optional[str] = None
    lane_code: Optional[str] = None
    eta: Optional[str] = None
    #: Hours to each chokepoint on the current routing. The timing that decides
    #: whether a diversion is still available.
    hours_to_chokepoint: Dict[str, float] = field(default_factory=dict)
    #: Slots still free, for the cargo layer.
    available_teu: float = 0.0
    available_reefer_plugs: int = 0
    accepts_hazardous: bool = False
    accepts_oog: bool = True
    #: Onward rotation after the current call.
    onward_ports: List[str] = field(default_factory=list)
    #: Where the position came from. Never inferred.
    position_source: str = SOURCE_SIMULATED
    lat: Optional[float] = None
    lon: Optional[float] = None
    cargo_value_index: float = 0.5

    def to_voyage(self) -> VesselVoyage:
        """The shape the Global Eye exposure graph consumes."""
        return VesselVoyage(
            vessel_id=self.vessel_id,
            name=self.name,
            lane_code=self.lane_code,
            destination_port=self.destination_port,
            hours_to_chokepoint=dict(self.hours_to_chokepoint),
            eta=self.eta,
            service_speed_kn=self.service_speed_kn,
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            **asdict(self),
            "laneName": (
                TRADE_LANES[self.lane_code].name if self.lane_code in TRADE_LANES else None
            ),
        }


@dataclass
class CompanyProfile:
    """A carrier account. The seam a real operator plugs into."""

    company_id: str
    name: str
    short_name: str
    #: True only for a real, contracted carrier account. Always False here.
    verified: bool
    home_ports: List[str] = field(default_factory=list)
    vessels: List[FleetVessel] = field(default_factory=list)
    #: What the fleet positions actually are.
    position_source: str = SOURCE_SIMULATED
    disclaimer: str = COMPANY_DISCLAIMER

    def vessel(self, vessel_id: str) -> Optional[FleetVessel]:
        return next((v for v in self.vessels if v.vessel_id == vessel_id), None)

    def voyages(self) -> List[VesselVoyage]:
        return [v.to_voyage() for v in self.vessels]

    def vessel_ids(self) -> List[str]:
        return [v.vessel_id for v in self.vessels]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "companyId": self.company_id,
            "name": self.name,
            "shortName": self.short_name,
            "verified": self.verified,
            "homePorts": self.home_ports,
            "vesselCount": len(self.vessels),
            "vessels": [v.to_dict() for v in self.vessels],
            "positionSource": self.position_source,
            "disclaimer": self.disclaimer,
        }


# --------------------------------------------------------------------------
# the demo fleet
# --------------------------------------------------------------------------

#: Vessel names from Indian Ocean geography. Chosen so nothing here collides
#: with an operating carrier's naming convention.
_NAMES: Tuple[str, ...] = (
    "Konkan", "Malabar", "Coromandel", "Kutch", "Deccan", "Sundarban",
    "Laccadive", "Andaman", "Nicobar", "Palk", "Cauvery", "Godavari",
    "Krishna", "Narmada", "Tapti", "Mahanadi", "Brahmaputra", "Zuari",
)

_CLASSES: Tuple[Tuple[str, float, float, float, int, int, float], ...] = (
    # (class, LOA, beam, draught, TEU, reefer plugs, service speed)
    ("feeder", 172.0, 27.0, 9.5, 1700, 150, 17.5),
    ("panamax", 250.0, 32.2, 12.0, 4500, 400, 21.0),
    ("post_panamax", 300.0, 40.0, 13.5, 8500, 700, 22.0),
    ("neo_panamax", 366.0, 51.0, 15.2, 14000, 1100, 21.5),
)

#: Lanes the demo fleet actually runs, with the chokepoint each transits.
_ROTATIONS: Tuple[Tuple[str, str, str, Tuple[str, ...]], ...] = (
    ("EUR_IND", "NLRTM", "INNSA", ("SGSIN", "AEJEA")),
    ("EUR_IND", "DEHAM", "INMUN", ("AEJEA", "OMSLL")),
    ("MED_IND", "ITGOA", "INNSA", ("LKCMB", "SGSIN")),
    ("GULF_IND", "AEJEA", "INNSA", ("INMUN", "INMRM")),
    ("GULF_IND", "QAHMD", "INVTZ", ("INMAA", "LKCMB")),
    ("SEA_IND", "SGSIN", "INMAA", ("INCCU", "BDCGP")),
    ("SEA_IND", "MYPKG", "INVTZ", ("INMAA", "LKCMB")),
    ("FE_IND", "CNSHA", "INNSA", ("AEJEA", "SGSIN")),
    ("FE_IND", "KRPUS", "INMAA", ("SGSIN", "MYPKG")),
    ("USEC_IND", "USNYC", "INNSA", ("AEJEA", "SGSIN")),
    ("COAST_W", "INCOK", "INNSA", ("INMUN", "INMRM")),
    ("COAST_E", "INCCU", "INMAA", ("INVTZ", "LKCMB")),
)

DEMO_COMPANY_ID = "portwatch-demo-shipping"


def demo_company(
    *,
    seed: int = 20260909,
    vessel_count: int = 14,
    company_id: str = DEMO_COMPANY_ID,
    name: str = "PortWatch Demo Shipping",
    short_name: str = "PWD",
) -> CompanyProfile:
    """Build the fictional demo carrier. Deterministic given the seed.

    Determinism matters here for the same reason it does in the traffic replay:
    the fleet screen has to show the same thing on every run, or a screenshot is
    not reviewable and a browser test is not stable.
    """
    rng = random.Random(seed)
    vessels: List[FleetVessel] = []

    for index in range(vessel_count):
        klass, loa, beam, draught, teu, plugs, speed = rng.choice(_CLASSES)
        lane_code, origin, destination, onward = _ROTATIONS[index % len(_ROTATIONS)]
        lane = TRADE_LANES.get(lane_code)

        # Hours to each chokepoint on the routing. Spread across the passage so
        # some vessels are still short of the strait, some are inside it and some
        # are through -- which is the whole point of the exposure timing gate.
        hours: Dict[str, float] = {}
        for position, chokepoint in enumerate(lane.chokepoints if lane else ()):
            # Negative means already past. A third of the fleet is, by design.
            base = rng.uniform(-40.0, 96.0)
            hours[chokepoint] = round(base + position * rng.uniform(20.0, 60.0), 1)

        loaded = rng.uniform(0.55, 0.94)
        vessels.append(
            FleetVessel(
                vessel_id=f"{short_name}-{index + 1:03d}",
                name=f"MV {_NAMES[index % len(_NAMES)]}",
                imo=None,
                vessel_class=klass,
                loa_m=loa,
                beam_m=beam,
                draught_m=draught * rng.uniform(0.88, 1.0),
                capacity_teu=teu,
                reefer_plugs=plugs,
                service_speed_kn=speed * rng.uniform(0.92, 1.02),
                flag="IN" if lane_code.startswith("COAST") else rng.choice(["SG", "MT", "PA", "IN"]),
                origin_port=origin,
                destination_port=destination,
                lane_code=lane_code,
                hours_to_chokepoint=hours,
                available_teu=round(teu * (1 - loaded), 0),
                available_reefer_plugs=int(plugs * (1 - loaded)),
                accepts_hazardous=rng.random() < 0.55,
                accepts_oog=rng.random() < 0.8,
                onward_ports=list(onward),
                position_source=SOURCE_SIMULATED,
                cargo_value_index=round(rng.uniform(0.3, 0.95), 2),
            )
        )

    return CompanyProfile(
        company_id=company_id,
        name=name,
        short_name=short_name,
        verified=False,
        home_ports=["INNSA", "INMAA", "INMUN"],
        vessels=vessels,
        position_source=SOURCE_SIMULATED,
    )


def attach_etas(profile: CompanyProfile, epoch_ms: int) -> CompanyProfile:
    """Give every vessel an ETA anchored to the pipeline's forecast origin.

    Anchoring to the pipeline clock rather than the wall clock keeps the fleet
    screen consistent with the port state it sits next to, and keeps a
    screenshot identical between runs.
    """
    from datetime import datetime, timedelta, timezone

    base = datetime.fromtimestamp(epoch_ms / 1000.0, tz=timezone.utc)
    for index, vessel in enumerate(profile.vessels):
        digest = int(hashlib.sha1(vessel.vessel_id.encode()).hexdigest()[:6], 16)
        hours = 6 + (digest % 96) + index * 0.7
        vessel.eta = (base + timedelta(hours=hours)).isoformat(timespec="seconds")
    return profile


def from_provider(payload: Dict[str, Any]) -> CompanyProfile:
    """Build a company profile from a real provider's payload.

    The seam. A licensed fleet-management or AIS provider maps its own schema
    onto this shape and everything downstream works unchanged -- exposure,
    cargo, advisories and the fleet screens all read :class:`CompanyProfile`.

    ``verified`` comes from the payload rather than being assumed: a provider
    that does not assert it is not treated as verified, and the UI then shows the
    same "demo" framing it does for the fictional carrier.
    """
    vessels = [
        FleetVessel(
            vessel_id=str(row["vesselId"]),
            name=str(row["name"]),
            imo=row.get("imo"),
            vessel_class=str(row.get("vesselClass", "container")),
            loa_m=float(row.get("loaM", 0.0)),
            beam_m=float(row.get("beamM", 0.0)),
            draught_m=float(row.get("draughtM", 0.0)),
            capacity_teu=int(row.get("capacityTeu", 0)),
            reefer_plugs=int(row.get("reeferPlugs", 0)),
            service_speed_kn=float(row.get("serviceSpeedKn", 16.0)),
            flag=str(row.get("flag", "")),
            origin_port=row.get("originPort"),
            destination_port=row.get("destinationPort"),
            lane_code=row.get("laneCode"),
            eta=row.get("eta"),
            hours_to_chokepoint={
                str(k): float(v) for k, v in (row.get("hoursToChokepoint") or {}).items()
            },
            available_teu=float(row.get("availableTeu", 0.0)),
            available_reefer_plugs=int(row.get("availableReeferPlugs", 0)),
            accepts_hazardous=bool(row.get("acceptsHazardous", False)),
            accepts_oog=bool(row.get("acceptsOog", False)),
            onward_ports=list(row.get("onwardPorts") or []),
            position_source=str(row.get("positionSource", SOURCE_PROVIDER)),
            lat=row.get("lat"),
            lon=row.get("lon"),
        )
        for row in (payload.get("vessels") or [])
    ]
    verified = bool(payload.get("verified", False))
    return CompanyProfile(
        company_id=str(payload["companyId"]),
        name=str(payload["name"]),
        short_name=str(payload.get("shortName", payload["name"][:3].upper())),
        verified=verified,
        home_ports=list(payload.get("homePorts") or []),
        vessels=vessels,
        position_source=str(payload.get("positionSource", SOURCE_PROVIDER)),
        disclaimer=(
            "" if verified else
            "Unverified carrier account. Positions and voyages come from the "
            "configured provider and have not been confirmed against a licensed "
            "AIS feed."
        ),
    )


def capacities_for(
    profile: CompanyProfile,
    *,
    port_code: Optional[str] = None,
    now_hour: float = 0.0,
) -> List[Any]:
    """Fleet vessels expressed as cargo capacity, for the transshipment layer."""
    from src.portwatch_os.cargo.model import VesselCapacity

    out: List[VesselCapacity] = []
    for index, vessel in enumerate(profile.vessels):
        if port_code and vessel.destination_port != port_code:
            continue
        # Sailing times are spread across the next three days so the connection
        # window is a live constraint rather than a formality. The first sailing
        # is far enough out that inbound cargo has time to make it -- otherwise
        # the earliest vessels are unusable and the window stops being the thing
        # under test.
        departure = now_hour + 18.0 + (index * 7.0) % 78.0
        out.append(
            VesselCapacity(
                vessel_id=vessel.vessel_id,
                name=vessel.name,
                available_teu=vessel.available_teu,
                available_reefer_plugs=vessel.available_reefer_plugs,
                accepts_hazardous=vessel.accepts_hazardous,
                accepts_oog=vessel.accepts_oog,
                onward_ports=list(vessel.onward_ports),
                departure_hour=departure,
                load_cutoff_hour=departure - 3.0,
                operator=profile.name,
            )
        )
    return out


__all__ = [
    "COMPANY_DISCLAIMER",
    "DEMO_COMPANY_ID",
    "SOURCE_LIVE_AIS",
    "SOURCE_PROVIDER",
    "SOURCE_SIMULATED",
    "CompanyProfile",
    "FleetVessel",
    "attach_etas",
    "capacities_for",
    "demo_company",
    "from_provider",
]
