"""The providers this deployment knows about, and the resolver over them.

Every entry states what is actually true today. A source with no adapter is
``PLANNED`` and says so; one with a seam but no key is ``CONFIGURABLE``; only
something this deployment really reads is ``AVAILABLE``. The temptation in a
registry like this is to list impressive names and let the reader assume they
are wired in, and a buyer who discovers otherwise stops believing the rest of
the product too.

Licence terms below are recorded from each provider's published terms as
understood at the time of writing. They are a starting point for a procurement
conversation, not legal advice, and `license.url` is carried so the current
terms can always be checked rather than trusted to this file.
"""

from __future__ import annotations

from datetime import datetime
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from src.portwatch_os.fabric.model import (
    AIS,
    AVAILABLE,
    COMMERCIAL,
    CONFIGURABLE,
    DAILY,
    DISASTER,
    ENTERPRISE,
    EVENTS,
    FIRE,
    FREE,
    FREEMIUM,
    GEOGRAPHY,
    HOURLY,
    MARINE,
    MODES,
    NEAR_REALTIME,
    PAID,
    PLANNED,
    PORT_STATS,
    ProviderDefinition,
    ProviderHealth,
    ProviderLicense,
    REALTIME,
    Resolution,
    SEISMIC,
    STATIC,
    VESSEL_REGISTRY,
    WEATHER,
)

#: Terms that permit commercial use and redistribution with attribution.
_OPEN = ProviderLicense(
    commercial_use=True,
    redistribution=True,
    attribution_required=True,
    summary="Open data; commercial use and redistribution permitted with attribution.",
)

#: Research-only terms. The whole reason this registry exists.
_NON_COMMERCIAL = ProviderLicense(
    commercial_use=False,
    redistribution=False,
    attribution_required=True,
    summary="Non-commercial use only. Not eligible for a paying deployment.",
)


def default_providers() -> List[ProviderDefinition]:
    """The catalogue, as it actually stands in this repository."""
    return [
        # ------------------------------------------------------- weather --
        ProviderDefinition(
            provider_id="open-meteo",
            name="Open-Meteo",
            capabilities=(WEATHER,),
            license=ProviderLicense(
                commercial_use=True,
                redistribution=True,
                attribution_required=True,
                summary=(
                    "Free for non-commercial use; commercial tiers available. "
                    "Attribution required."
                ),
                url="https://open-meteo.com/en/terms",
            ),
            status=AVAILABLE,
            latency_class=HOURLY,
            cost_class=FREEMIUM,
            coverage="global",
            trust=0.78,
            notes="The forecast surface the weather layer and the twin already read.",
        ),
        ProviderDefinition(
            provider_id="open-meteo-marine",
            name="Open-Meteo Marine",
            capabilities=(MARINE,),
            license=ProviderLicense(
                commercial_use=True,
                redistribution=True,
                attribution_required=True,
                summary="As Open-Meteo. Wave height, swell, SST and currents.",
                url="https://open-meteo.com/en/docs/marine-weather-api",
            ),
            status=CONFIGURABLE,
            latency_class=HOURLY,
            cost_class=FREEMIUM,
            coverage="global oceans",
            trust=0.7,
            fallbacks=("open-meteo",),
            notes=(
                "Wave and swell fields the environment layer does not yet draw. "
                "No adapter is wired; the seam is the weather service."
            ),
        ),

        # ----------------------------------------------------------- AIS --
        ProviderDefinition(
            provider_id="ais-replay",
            name="Deterministic AIS replay",
            capabilities=(AIS,),
            license=ProviderLicense(
                commercial_use=True,
                redistribution=True,
                attribution_required=False,
                summary=(
                    "Generated by this project. Simulated positions, labelled as "
                    "such on every surface."
                ),
            ),
            status=AVAILABLE,
            latency_class=STATIC,
            cost_class=FREE,
            coverage="Indian Ocean traffic model",
            trust=0.35,
            synthetic=True,
            notes=(
                "Not observed traffic and never presented as such. It exists so "
                "the product is demonstrable without an AIS licence."
            ),
        ),
        ProviderDefinition(
            provider_id="aisstream",
            name="AISStream",
            capabilities=(AIS,),
            license=ProviderLicense(
                commercial_use=False,
                redistribution=False,
                attribution_required=True,
                summary=(
                    "Free community AIS. Not licensed as a commercial production "
                    "backbone."
                ),
                url="https://aisstream.io/",
            ),
            status=CONFIGURABLE,
            latency_class=REALTIME,
            cost_class=FREE,
            coverage="global, coverage varies by receiver density",
            auth_required=True,
            trust=0.6,
            fallbacks=("ais-replay",),
            notes=(
                "Suitable for the student and demo builds. Deliberately barred "
                "from COMMERCIAL by its licence rather than by a code path."
            ),
        ),
        ProviderDefinition(
            provider_id="spire",
            name="Spire Maritime",
            capabilities=(AIS, VESSEL_REGISTRY),
            license=ProviderLicense(
                commercial_use=True,
                redistribution=False,
                attribution_required=False,
                summary=(
                    "Commercial satellite and terrestrial AIS under contract. "
                    "Redistribution terms are per-agreement."
                ),
                url="https://spire.com/maritime/",
            ),
            status=PLANNED,
            latency_class=NEAR_REALTIME,
            cost_class=ENTERPRISE,
            coverage="global",
            auth_required=True,
            trust=0.9,
            notes="No adapter exists. Named so the commercial path is visible.",
        ),
        ProviderDefinition(
            provider_id="kpler",
            name="Kpler",
            capabilities=(AIS, PORT_STATS, VESSEL_REGISTRY),
            license=ProviderLicense(
                commercial_use=True,
                redistribution=False,
                attribution_required=False,
                summary="Commercial vessel tracking and port activity under contract.",
                url="https://www.kpler.com/",
            ),
            status=PLANNED,
            latency_class=NEAR_REALTIME,
            cost_class=ENTERPRISE,
            coverage="global",
            auth_required=True,
            trust=0.9,
            notes="No adapter exists.",
        ),
        ProviderDefinition(
            provider_id="global-fishing-watch",
            name="Global Fishing Watch",
            capabilities=(VESSEL_REGISTRY,),
            license=ProviderLicense(
                commercial_use=False,
                redistribution=False,
                attribution_required=True,
                summary=(
                    "APIs are for non-commercial purposes. Excellent for research "
                    "and government work; cannot back a commercial deployment."
                ),
                url="https://globalfishingwatch.org/our-apis/documentation/",
            ),
            status=PLANNED,
            latency_class=DAILY,
            cost_class=FREE,
            coverage="global",
            auth_required=True,
            trust=0.85,
            notes=(
                "Identity across 40+ registries, AIS-gap and encounter events. "
                "The clearest example of why licence is a first-class field: it "
                "is one of the best sources available and is barred from "
                "COMMERCIAL and GOVERNMENT alike."
            ),
        ),

        # -------------------------------------------------------- events --
        ProviderDefinition(
            provider_id="gdelt",
            name="GDELT",
            capabilities=(EVENTS,),
            license=_OPEN,
            status=AVAILABLE,
            latency_class=NEAR_REALTIME,
            cost_class=FREE,
            coverage="global news",
            trust=0.55,
            notes="The feed Global Eye ingests and merges into the event register.",
        ),
        ProviderDefinition(
            provider_id="gdacs",
            name="GDACS",
            capabilities=(DISASTER,),
            license=_OPEN,
            status=CONFIGURABLE,
            latency_class=HOURLY,
            cost_class=FREE,
            coverage="global disasters",
            trust=0.75,
            fallbacks=("gdelt",),
            notes="Disaster alerts. No adapter wired yet.",
        ),
        ProviderDefinition(
            provider_id="usgs",
            name="USGS earthquakes",
            capabilities=(SEISMIC,),
            license=_OPEN,
            status=CONFIGURABLE,
            latency_class=NEAR_REALTIME,
            cost_class=FREE,
            coverage="global",
            trust=0.95,
            notes="Public seismic feed. No adapter wired yet.",
        ),
        ProviderDefinition(
            provider_id="nasa-firms",
            name="NASA FIRMS",
            capabilities=(FIRE,),
            license=_OPEN,
            status=PLANNED,
            latency_class=NEAR_REALTIME,
            cost_class=FREE,
            coverage="global",
            auth_required=True,
            trust=0.85,
            notes="Active fire detections. No adapter exists.",
        ),

        # ---------------------------------------------------- port stats --
        ProviderDefinition(
            provider_id="imf-portwatch",
            name="IMF PortWatch",
            capabilities=(PORT_STATS,),
            license=_OPEN,
            status=AVAILABLE,
            latency_class=DAILY,
            cost_class=FREE,
            coverage="global ports",
            trust=0.8,
            notes="Port call and throughput statistics behind the port registry.",
        ),

        # ----------------------------------------------------- geography --
        ProviderDefinition(
            provider_id="natural-earth",
            name="Natural Earth",
            capabilities=(GEOGRAPHY,),
            license=ProviderLicense(
                commercial_use=True,
                redistribution=True,
                attribution_required=False,
                summary="Public domain.",
                url="https://www.naturalearthdata.com/about/terms-of-use/",
            ),
            status=AVAILABLE,
            latency_class=STATIC,
            cost_class=FREE,
            coverage="global",
            trust=1.0,
            notes="Coastlines and borders the chart draws.",
        ),
    ]


class SignalFabric:
    """The provider registry, and the mode-aware resolver over it."""

    def __init__(
        self,
        providers: Optional[Sequence[ProviderDefinition]] = None,
        *,
        mode: str = COMMERCIAL,
    ) -> None:
        if mode not in MODES:
            raise ValueError(f"{mode!r} is not a deployment mode")
        self.mode = mode
        self._providers: Dict[str, ProviderDefinition] = {
            p.provider_id: p for p in (providers if providers is not None else default_providers())
        }

    # -- reading ---------------------------------------------------------
    def get(self, provider_id: str) -> Optional[ProviderDefinition]:
        return self._providers.get(provider_id)

    def providers(self, *, capability: Optional[str] = None) -> List[ProviderDefinition]:
        rows = list(self._providers.values())
        if capability:
            rows = [p for p in rows if capability in p.capabilities]
        return sorted(rows, key=lambda p: p.provider_id)

    # -- resolution ------------------------------------------------------
    def resolve(
        self,
        capability: str,
        *,
        mode: Optional[str] = None,
        now: Optional[datetime] = None,
    ) -> Resolution:
        """The best legally usable provider for a capability, or UNAVAILABLE.

        Ordered by trust, then by how fresh the source actually is, then by how
        little it costs -- in that order, because a cheaper source that is wrong
        is not cheaper. Everything rejected is returned with its reason, which
        is what makes this auditable rather than merely automatic.

        There is deliberately no silent fallback across a licence boundary. If
        the only AIS a COMMERCIAL deployment has is non-commercial, the answer
        is UNAVAILABLE and the reason says so.
        """
        active = mode or self.mode
        if active not in MODES:
            raise ValueError(f"{active!r} is not a deployment mode")

        eligible: List[ProviderDefinition] = []
        rejected: List[Tuple[str, str]] = []
        for provider in self.providers(capability=capability):
            ok, reason = provider.eligible_for(active, capability)
            if ok:
                eligible.append(provider)
            elif reason:
                rejected.append((provider.provider_id, reason))

        if not eligible:
            return Resolution(
                capability=capability, mode=active, provider=None,
                rejected=tuple(rejected),
            )

        freshness_rank = {"fresh": 0, "unknown": 1, "stale": 2, "cold": 3}
        cost_rank = {FREE: 0, FREEMIUM: 1, PAID: 2, ENTERPRISE: 3}
        eligible.sort(
            key=lambda p: (
                -p.trust,
                freshness_rank.get(p.health.freshness(now=now), 1),
                cost_rank.get(p.cost_class, 9),
                p.provider_id,
            )
        )
        chosen = eligible[0]
        for other in eligible[1:]:
            rejected.append((other.provider_id, f"{chosen.name} ranked higher"))
        return Resolution(
            capability=capability, mode=active, provider=chosen,
            rejected=tuple(rejected),
        )

    def report(self, *, now: Optional[datetime] = None) -> Dict[str, object]:
        """Every capability, and what would serve it in this mode."""
        from src.portwatch_os.fabric.model import CAPABILITIES

        return {
            "mode": self.mode,
            "providers": [p.to_dict(now=now) for p in self.providers()],
            "resolution": {
                capability: self.resolve(capability, now=now).to_dict(now=now)
                for capability in CAPABILITIES
            },
        }


_DEFAULT: Optional[SignalFabric] = None


def get_fabric(mode: str = COMMERCIAL) -> SignalFabric:
    """The process-wide fabric. Mode is a deployment property, not a request one."""
    global _DEFAULT
    if _DEFAULT is None or _DEFAULT.mode != mode:
        _DEFAULT = SignalFabric(mode=mode)
    return _DEFAULT


__all__ = ["SignalFabric", "default_providers", "get_fabric"]
