/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ModelRouteImport } from './routes/model'
import { Route as NlpRouteImport } from './routes/nlp'
import { Route as PortRouteImport } from './routes/port'
import { Route as SarRouteImport } from './routes/sar'
import { Route as SimRouteImport } from './routes/sim'
import { Route as WxRouteImport } from './routes/wx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const NlpRoute = NlpRouteImport.update({
  id: '/nlp',
  path: '/nlp',
  getParentRoute: () => rootRouteImport,
} as any)
const PortRoute = PortRouteImport.update({
  id: '/port',
  path: '/port',
  getParentRoute: () => rootRouteImport,
} as any)
const SarRoute = SarRouteImport.update({
  id: '/sar',
  path: '/sar',
  getParentRoute: () => rootRouteImport,
} as any)
const SimRoute = SimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => rootRouteImport,
} as any)
const WxRoute = WxRouteImport.update({
  id: '/wx',
  path: '/wx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fleet': typeof FleetRoute
  '/model': typeof ModelRoute
  '/nlp': typeof NlpRoute
  '/port': typeof PortRoute
  '/sar': typeof SarRoute
  '/sim': typeof SimRoute
  '/wx': typeof WxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fleet': typeof FleetRoute
  '/model': typeof ModelRoute
  '/nlp': typeof NlpRoute
  '/port': typeof PortRoute
  '/sar': typeof SarRoute
  '/sim': typeof SimRoute
  '/wx': typeof WxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fleet': typeof FleetRoute
  '/model': typeof ModelRoute
  '/nlp': typeof NlpRoute
  '/port': typeof PortRoute
  '/sar': typeof SarRoute
  '/sim': typeof SimRoute
  '/wx': typeof WxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/fleet' | '/model' | '/nlp' | '/port' | '/sar' | '/sim' | '/wx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fleet' | '/model' | '/nlp' | '/port' | '/sar' | '/sim' | '/wx'
  id:
    | '__root__'
    | '/'
    | '/fleet'
    | '/model'
    | '/nlp'
    | '/port'
    | '/sar'
    | '/sim'
    | '/wx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FleetRoute: typeof FleetRoute
  ModelRoute: typeof ModelRoute
  NlpRoute: typeof NlpRoute
  PortRoute: typeof PortRoute
  SarRoute: typeof SarRoute
  SimRoute: typeof SimRoute
  WxRoute: typeof WxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nlp': {
      id: '/nlp'
      path: '/nlp'
      fullPath: '/nlp'
      preLoaderRoute: typeof NlpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port': {
      id: '/port'
      path: '/port'
      fullPath: '/port'
      preLoaderRoute: typeof PortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sar': {
      id: '/sar'
      path: '/sar'
      fullPath: '/sar'
      preLoaderRoute: typeof SarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim': {
      id: '/sim'
      path: '/sim'
      fullPath: '/sim'
      preLoaderRoute: typeof SimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wx': {
      id: '/wx'
      path: '/wx'
      fullPath: '/wx'
      preLoaderRoute: typeof WxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FleetRoute: FleetRoute,
  ModelRoute: ModelRoute,
  NlpRoute: NlpRoute,
  PortRoute: PortRoute,
  SarRoute: SarRoute,
  SimRoute: SimRoute,
  WxRoute: WxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
