/**
 * The traffic contract.
 *
 * One shape for a vessel on the map, and one enumeration for where it came
 * from. Every screen consumes `VesselFix` and asks the source what it is; no
 * screen knows whether the positions behind it were received over a live AIS
 * link or produced by the replay engine. Swapping a real provider in later is a
 * new implementation of `TrafficSource` and nothing else.
 */

import type { Position } from "./geo";

/* ---------------------------------------------------------------- source -- */

/**
 * Where positions come from. This is the honesty seam of the whole traffic
 * layer, and it is never inferred: a source declares its own kind.
 *
 *   LIVE_AIS            a terrestrial or satellite AIS provider, streaming.
 *   AIS_REPLAY          recorded AIS positions, replayed against a clock.
 *   SIMULATED_TRAFFIC   positions generated by this application. Not observed.
 *   UNAVAILABLE         no provider is configured or reachable.
 */
export type TrafficSourceKind =
  | "LIVE_AIS"
  | "AIS_REPLAY"
  | "SIMULATED_TRAFFIC"
  | "UNAVAILABLE";

export interface TrafficSourceInfo {
  kind: TrafficSourceKind;
  /** Two or three words for the status strip. */
  label: string;
  provider: string;
  /** One sentence a reader can act on: what this is, and what it is not. */
  detail: string;
  /** Wall-clock instant the replay clock is anchored to. */
  epoch: number;
  /** True only when positions were actually observed by a receiver. */
  observed: boolean;
}

/* --------------------------------------------------------------- vessels -- */

export type VesselClass =
  | "container"
  | "tanker"
  | "bulk"
  | "lng"
  | "roro"
  | "cargo"
  | "passenger"
  | "service";

export type NavStatus =
  | "underway"
  | "inbound"
  | "outbound"
  | "anchored"
  | "waiting"
  | "moored"
  | "service";

export interface VesselClassSpec {
  key: VesselClass;
  label: string;
  /** Service speed range in knots, from published class envelopes. */
  speedKn: [number, number];
  lengthM: [number, number];
  /** Marker fill. Class, not state -- state is carried by the glyph. */
  color: string;
  /** Relative share of a general cargo mix, used when a leg has no bias. */
  share: number;
}

export const VESSEL_CLASSES: Record<VesselClass, VesselClassSpec> = {
  container: {
    key: "container",
    label: "Container",
    speedKn: [14, 22],
    lengthM: [180, 366],
    color: "#57a9d8",
    share: 0.3,
  },
  tanker: {
    key: "tanker",
    label: "Tanker",
    speedKn: [10, 16],
    lengthM: [180, 333],
    color: "#cf8b4a",
    share: 0.22,
  },
  bulk: {
    key: "bulk",
    label: "Bulk carrier",
    speedKn: [10, 15],
    lengthM: [170, 292],
    color: "#93b062",
    share: 0.2,
  },
  lng: {
    key: "lng",
    label: "LNG / LPG",
    speedKn: [15, 19],
    lengthM: [230, 315],
    color: "#9d86d6",
    share: 0.06,
  },
  roro: {
    key: "roro",
    label: "RoRo / vehicle",
    speedKn: [15, 20],
    lengthM: [150, 265],
    color: "#57b3a5",
    share: 0.06,
  },
  cargo: {
    key: "cargo",
    label: "General cargo",
    speedKn: [11, 16],
    lengthM: [90, 190],
    color: "#93a7b8",
    share: 0.1,
  },
  passenger: {
    key: "passenger",
    label: "Passenger",
    speedKn: [16, 22],
    lengthM: [120, 260],
    color: "#d5758f",
    share: 0.02,
  },
  service: {
    key: "service",
    label: "Service / tug",
    speedKn: [4, 12],
    lengthM: [24, 80],
    color: "#7a8fa1",
    share: 0.04,
  },
};

export const VESSEL_CLASS_LIST = Object.values(VESSEL_CLASSES);

export const NAV_STATUS_LABEL: Record<NavStatus, string> = {
  underway: "Underway",
  inbound: "Inbound",
  outbound: "Outbound",
  anchored: "Anchored",
  waiting: "Waiting",
  moored: "Moored",
  service: "Service",
};

/** Static particulars — everything that does not change between fixes. */
export interface Vessel {
  id: string;
  /** Callable identity in the replay. Never an IMO number: none was issued. */
  replayId: string;
  imo: string | null;
  name: string;
  operator: string;
  callsign: string;
  flag: string;
  vesselClass: VesselClass;
  lengthM: number;
  beamM: number;
  draughtM: number;
  dwt: number;
  /** Waypoint ids for the current voyage. */
  originId: string;
  destinationId: string;
  /** Waypoint id of the Indian port this vessel is operationally attached to. */
  homePortId: string | null;
  serviceSpeedKn: number;
  /** True for a vessel the signed-in operator owns. */
  owned: boolean;
}

/** A vessel resolved to an instant. */
export interface VesselFix extends Vessel {
  at: number;
  lon: number;
  lat: number;
  /** Course over ground, degrees true. */
  cog: number;
  /** Heading, degrees true. Equal to COG under way; it is a replay. */
  heading: number;
  sogKn: number;
  status: NavStatus;
  /** 0 at the origin quay, 1 at the destination quay. */
  progress: number;
  travelledKm: number;
  remainingKm: number;
  /**
   * The vessel's next scheduled event, epoch ms. What that event is depends on
   * where the vessel is, and `etaKind` says which -- a port controller reading
   * a row needs to know whether 14:20 is an arrival off the fairway buoy or the
   * moment a berth frees up.
   */
  etaMs: number | null;
  etaMinutes: number | null;
  etaKind: "arrival" | "berthing" | "departure" | null;
  /** The passage this vessel is running, oriented origin to destination. */
  routeKey: string | null;
}

/* ---------------------------------------------------------------- source -- */

export interface TrafficSource {
  readonly info: TrafficSourceInfo;
  /** Static particulars for the whole fleet. */
  roster(): Vessel[];
  /** Every vessel resolved to `at`, in epoch milliseconds. */
  fixes(at: number): VesselFix[];
  /** One vessel resolved to `at`, or null if the id is unknown. */
  fix(id: string, at: number): VesselFix | null;
  /** The passage geometry for a vessel, or null where none applies. */
  route(id: string): { coords: Position[]; km: number } | null;
}
